export const testSeeds = [
  { title: 'donJose', count: 5, picture: 'https://donJose.com', enabled: true },
  { title: 'about', count: 2, picture: 'https://about.com/img1', enabled: true },
  { title: 'contact', count: 7, picture: 'https://contact.com/img2', enabled: false },
  { title: 'services', count: 1, picture: 'https://services.com/img3', enabled: true },
  { title: 'portfolio', count: 9, picture: 'https://portfolio.com/img4', enabled: false },
  { title: 'home', count: 3, picture: 'https://home.com/img5', enabled: true },
  { title: 'products', count: 12, picture: 'https://products.com/img6', enabled: true },
  { title: 'team', count: 6, picture: 'https://team.com/img7', enabled: false },
  { title: 'careers', count: 0, picture: 'https://careers.com/img8', enabled: true },
  { title: 'blog', count: 4, picture: 'https://blog.com/img9', enabled: true },
  { title: 'faq', count: 10, picture: 'https://faq.com/img10', enabled: false },
  { title: 'support', count: 8, picture: 'https://support.com/img11', enabled: true },
  { title: 'terms', count: 15, picture: 'https://terms.com/img12', enabled: false },
  { title: 'privacy', count: 11, picture: 'https://privacy.com/img13', enabled: true },
  { title: 'login', count: 14, picture: 'https://login.com/img14', enabled: true },
  { title: 'register', count: 13, picture: 'https://register.com/img15', enabled: false },
  { title: 'dashboard', count: 17, picture: 'https://dashboard.com/img16', enabled: true },
  { title: 'settings', count: 16, picture: 'https://settings.com/img17', enabled: true },
  { title: 'notifications', count: 18, picture: 'https://notifications.com/img18', enabled: false },
  { title: 'messages', count: 19, picture: 'https://messages.com/img19', enabled: true },
  { title: 'billing', count: 21, picture: 'https://billing.com/img20', enabled: true },
  { title: 'reports', count: 22, picture: 'https://reports.com/img21', enabled: false },
  { title: 'analytics', count: 23, picture: 'https://analytics.com/img22', enabled: true },
  { title: 'integration', count: 24, picture: 'https://integration.com/img23', enabled: true },
  { title: 'feedback', count: 20, picture: 'https://feedback.com/img24', enabled: false }
]
